### PR TITLE
Update README with structure

### PR DESCRIPTION
**Pull request by kenjishiromajp**
I updated the README with structure, guys see it and make your considerations. :)

### CODE REVIEW

**Comment by wendelnascimento** [comment]
@kenjishiromajp Thanks for the contribution. What do you think about also add a babelrc file and a flowtype configuration file?

**Comment by kenjishiromajp** [comment]
I agree with babelrc, but about flowtype I never used it before...

**Comment by wendelnascimento** [comment]
Don't you think it's time to give it a shot? lol

**Comment by wendelnascimento** [comment]
I'm merging with .babelrc change. Maybe we have to create a separate branch to test if adding flowtype it's worthy

**Pull request merged**
